// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DtoWindow
{
    internal sealed partial class Vsix
    {
        public const string Id = "DtoWindow.a5cc5891-fcf3-4d72-a4d8-186de9b650a9";
        public const string Name = "DtoWindow";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "climax85";
        public const string Tags = "";
    }
}
